from psychopy import visual, core

win = visual.Window([400,400])
message = visual.TextStim(win, text='Hello from :')
message.setAutoDraw(True)
win.flip()
core.wait(2.0)
message.setText('umar')
win.flip()
core.wait(2.0)
message.setText('known as:')
win.flip()
core.wait(2.0)
message.setText('pyc0d3r')
win.flip()
core.wait(2.0)
message.setText('His website')
win.flip()
core.wait(2.0)
message.setText('http://www.umarbrowser.co.vu/')
win.flip()
core.wait(2.0)